# Final Project Data Exploration

The purpose of this notebook is to identify any data cleaning that needs to be done on the various data sources used in my final project.

The goal of my project is to combine air quality sensor data, meteorological data, and health survey data from the National Health Interview Survey. Each section of this notebook will cover the process of asessing data quality for each source so that any data cleaning processes can be incorporated into the ETL process.

## Section 1: Daily PM 2.5 Data

The data being considered here is a subset of the total data to be modeled. I am using only data from 2018 in the EDA process.

In [126]:
import pandas as pd

In [39]:
# read in the csv file
df1 = pd.read_csv('daily_88101_2018/daily_88101_2018.csv')
# show the columns for reference
df1.columns

Index(['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC',
       'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration',
       'Pollutant Standard', 'Date Local', 'Units of Measure', 'Event Type',
       'Observation Count', 'Observation Percent', 'Arithmetic Mean',
       '1st Max Value', '1st Max Hour', 'AQI', 'Method Code', 'Method Name',
       'Local Site Name', 'Address', 'State Name', 'County Name', 'City Name',
       'CBSA Name', 'Date of Last Change'],
      dtype='object')

In [40]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521560 entries, 0 to 521559
Data columns (total 29 columns):
State Code             521560 non-null int64
County Code            521560 non-null int64
Site Num               521560 non-null int64
Parameter Code         521560 non-null int64
POC                    521560 non-null int64
Latitude               521560 non-null float64
Longitude              521560 non-null float64
Datum                  521560 non-null object
Parameter Name         521560 non-null object
Sample Duration        521560 non-null object
Pollutant Standard     299297 non-null object
Date Local             521560 non-null object
Units of Measure       521560 non-null object
Event Type             521560 non-null object
Observation Count      521560 non-null int64
Observation Percent    521560 non-null float64
Arithmetic Mean        521560 non-null float64
1st Max Value          521560 non-null float64
1st Max Hour           521560 non-null int64
AQI                    299297 non-null float64
Method Code            314019 non-null float64
Method Name            521560 non-null object
Local Site Name        497804 non-null object
Address                521560 non-null object
State Name             521560 non-null object
County Name            521560 non-null object
City Name              521560 non-null object
CBSA Name              481780 non-null object
Date of Last Change    521560 non-null object
dtypes: float64(7), int64(7), object(15)
memory usage: 115.4+ MB

In [130]:
len(df1.Address.unique())

1000

In [139]:
len(df1[['Latitude','Longitude']].drop_duplicates())

1001

The fields that contain missing values are:
1. Pollutant Standard: Indicates how the pollutant values are calcualted. The standard for PM 2.5 is 24 hour averages. A number of the rows contain 1 hour PM 2.5 readings. These are non-standard readings and have no AQI associated with them.
2. AQI: Air quality index for the day
3. Method Code: An internal system code indicating the method (processes, equipment, and protocols) used in gathering and measuring the sample.
4. Local Site Name: Data documentation indicates that this may or may not exist
5. CBSA Name: core bases statistical area (metropolitan area), it may be possible that some stations are not located in a CBSA.

I want the data going into the database to be comparable to the standard way of calculating PM 2.5 pollution. One step of the data cleaning process will be to remove all rows that are not reporting PM 2.5 levels in the standard format. The Pollutant Standard column contains information about what the standard measurement should be for the pollutant.

In [41]:
df1['Pollutant Standard'].unique()

array(['PM25 24-hour 2012', nan], dtype=object)

The pollutant standard is a 24-hour average of PM 2.5 concentations. Another column, Sample Duration, indicates how long the sample was collected for the reported PM 2.5 reading. Any values that are not 24 hour averages should be dropped. We can also see if they line up with NaN vlaues for Pollutant Standard.

In [42]:
df1.groupby(['Pollutant Standard','Sample Duration'])['State Code'].count()

Pollutant Standard  Sample Duration
PM25 24-hour 2012   24 HOUR             91756
                    24-HR BLK AVG      207541
Name: State Code, dtype: int64

It looks like there are 2 sample duration values that are included in the rows that have the Pollutant Standard indicated. Both are 24 hour measurement times. Therefore, part of the data cleaning will include filtering on the Pollutant Stnadard column and removing any null rows.

In [43]:
df1 = df1.dropna(axis=0, subset=['Pollutant Standard'])

Inspecting the remaining data in df with `df.info()` shows that some rows are still missing values in the same columns identified above. Importantly, there are no missing values for the PM 2.5 readings or the AQI values. Some rows are still missing site names or CBSA names, but I believe that those are not mistakes. At this point, I do not intend to retain that information in the final data model anyway. Instead, I am choosing to retain the state, county, city, latitude, and longitude as dimensions for spatial analysis.

## Section 2: Daily Barometric Pressure

In [44]:
df2 = pd.read_csv('daily_PRESS_2018.zip', )

In [45]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109976 entries, 0 to 109975
Data columns (total 29 columns):
State Code             109976 non-null int64
County Code            109976 non-null int64
Site Num               109976 non-null int64
Parameter Code         109976 non-null int64
POC                    109976 non-null int64
Latitude               109976 non-null float64
Longitude              109976 non-null float64
Datum                  109976 non-null object
Parameter Name         109976 non-null object
Sample Duration        109976 non-null object
Pollutant Standard     0 non-null float64
Date Local             109976 non-null object
Units of Measure       109976 non-null object
Event Type             109976 non-null object
Observation Count      109976 non-null int64
Observation Percent    109976 non-null float64
Arithmetic Mean        109976 non-null float64
1st Max Value          109976 non-null float64
1st Max Hour           109976 non-null int64
AQI                    0 non-null float64
Method Code            109976 non-null int64
Method Name            109976 non-null object
Local Site Name        99570 non-null object
Address                109976 non-null object
State Name             109976 non-null object
County Name            109976 non-null object
City Name              109976 non-null object
CBSA Name              95187 non-null object
Date of Last Change    109976 non-null object
dtypes: float64(7), int64(8), object(14)
memory usage: 24.3+ MB

Looking that the different columns, it looks like almost all the data is present. There is no Pollutant Standard because barometric pressure is not a pollutant. There are no AQI values because the AQI cannot be calculated from this measurement. Some CBSA Names are missing but I do not plan to include this information in the final data model.

In [54]:
df2['Sample Duration'].unique()

array(['1 HOUR'], dtype=object)

The sample duration for the pressure readings are 1 hour, so I will need to downsmple these data. However, I need to check that there are actually 24 samples per day per sensor. If there are only 1 per day per sensor, I will assume that hourly readings have already been averaged per day.

In [55]:
df2[['Date Local', 'Local Site Name', 'Arithmetic Mean']].sort_values(by=['Date Local','Local Site Name']).head()

,Date Local,Local Site Name,Arithmetic Mean
82949,2018-01-01,FRANCIS SCHOOL East Providence,1019.458333
28834,2018-01-01,"10 METER TOWER, AT NW CORNER, U OF I RESEARCH ...",951.041667
68116,2018-01-01,4102 Woolworth Ave. on Healthcenter Warehouse,993.108333
33124,2018-01-01,416 S. State St. Hwy 1- West Union,1023.875000
56818,2018-01-01,"6792 RAISIN CENTER HWY, LENAWEE CO.RD.COMM.OWN...",1001.083333

Because there is only one reading per Local Site Name, I assume that these data have lready been downsampled. No additional cleaning looks to be needed for the pressure data.

## Section 3: Relative Humidity and Dew Point

In [51]:
df3 = pd.read_csv('daily_RH_DP_2018.zip')

In [52]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171311 entries, 0 to 171310
Data columns (total 29 columns):
State Code             171311 non-null int64
County Code            171311 non-null int64
Site Num               171311 non-null int64
Parameter Code         171311 non-null int64
POC                    171311 non-null int64
Latitude               171311 non-null float64
Longitude              171311 non-null float64
Datum                  171311 non-null object
Parameter Name         171311 non-null object
Sample Duration        171311 non-null object
Pollutant Standard     0 non-null float64
Date Local             171311 non-null object
Units of Measure       171311 non-null object
Event Type             171311 non-null object
Observation Count      171311 non-null int64
Observation Percent    171311 non-null float64
Arithmetic Mean        171311 non-null float64
1st Max Value          171311 non-null float64
1st Max Hour           171311 non-null int64
AQI                    0 non-null float64
Method Code            171311 non-null int64
Method Name            171311 non-null object
Local Site Name        155901 non-null object
Address                171083 non-null object
State Name             171311 non-null object
County Name            171311 non-null object
City Name              171311 non-null object
CBSA Name              150357 non-null object
Date of Last Change    171311 non-null object
dtypes: float64(7), int64(8), object(14)
memory usage: 37.9+ MB

In [53]:
df3['Sample Duration'].unique()

array(['1 HOUR'], dtype=object)

The RH data looks like I will be ale to treat it the same as the pressure data in terms of cleaning. Let's check if the rows are split by humidity or dew point readings to make sure we don't mix values.

In [57]:
df3['Parameter Name'].unique()

array(['Relative Humidity ', 'Dew Point'], dtype=object)

So we can see that there are two different types of data in this same table. When processing the data we will need to split these input tables based on the sample type.

## Section 4: Temp

In [59]:
df4 = pd.read_csv('daily_TEMP_2018.zip')
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303287 entries, 0 to 303286
Data columns (total 29 columns):
State Code             303287 non-null int64
County Code            303287 non-null int64
Site Num               303287 non-null int64
Parameter Code         303287 non-null int64
POC                    303287 non-null int64
Latitude               303287 non-null float64
Longitude              303287 non-null float64
Datum                  303287 non-null object
Parameter Name         303287 non-null object
Sample Duration        303287 non-null object
Pollutant Standard     0 non-null float64
Date Local             303287 non-null object
Units of Measure       303287 non-null object
Event Type             303287 non-null object
Observation Count      303287 non-null int64
Observation Percent    303287 non-null float64
Arithmetic Mean        303287 non-null float64
1st Max Value          303287 non-null float64
1st Max Hour           303287 non-null int64
AQI                    0 non-null float64
Method Code            303287 non-null int64
Method Name            303287 non-null object
Local Site Name        282482 non-null object
Address                302831 non-null object
State Name             303287 non-null object
County Name            303287 non-null object
City Name              303287 non-null object
CBSA Name              267969 non-null object
Date of Last Change    303287 non-null object
dtypes: float64(7), int64(8), object(14)
memory usage: 67.1+ MB

As with the other meteoroligical data, most of the data appears to be present. Let's double check the values to make sure that we know what time sampling we are working with and if there are different units of measurement.

In [60]:
df4['Sample Duration'].unique()

array(['1 HOUR'], dtype=object)

Looks like 1 hour samples averaged out over 24 hours.

In [61]:
df4['Parameter Name'].unique()

array(['Outdoor Temperature'], dtype=object)

All the values are the same parameter, so we don't need to split based on this.

## Section 5: Wind

Finally, let's check the wind data quality.

In [63]:
df5 = pd.read_csv('daily_WIND_2018.zip')
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497192 entries, 0 to 497191
Data columns (total 29 columns):
State Code             497192 non-null int64
County Code            497192 non-null int64
Site Num               497192 non-null int64
Parameter Code         497192 non-null int64
POC                    497192 non-null int64
Latitude               497192 non-null float64
Longitude              497192 non-null float64
Datum                  497192 non-null object
Parameter Name         497192 non-null object
Sample Duration        497192 non-null object
Pollutant Standard     0 non-null float64
Date Local             497192 non-null object
Units of Measure       497192 non-null object
Event Type             497192 non-null object
Observation Count      497192 non-null int64
Observation Percent    497192 non-null float64
Arithmetic Mean        497192 non-null float64
1st Max Value          497192 non-null float64
1st Max Hour           497192 non-null int64
AQI                    0 non-null float64
Method Code            497192 non-null int64
Method Name            497192 non-null object
Local Site Name        471612 non-null object
Address                496964 non-null object
State Name             497192 non-null object
County Name            497192 non-null object
City Name              497192 non-null object
CBSA Name              454346 non-null object
Date of Last Change    497192 non-null object
dtypes: float64(7), int64(8), object(14)
memory usage: 110.0+ MB

In [65]:
df5['Sample Duration'].unique()

array(['1 HOUR'], dtype=object)

In [66]:
df5['Parameter Name'].unique()

array(['Wind Speed - Resultant', 'Wind Direction - Resultant'],
      dtype=object)

In [140]:
df5['Units of Measure'].unique()

array(['Knots', 'Degrees Compass'], dtype=object)

The wind data is collected hourly and provided as the average of those values over 24 hours. There are two different parameters that make up the wind information, the speed and the direcation. The wind tables will need to be split by these different parameter names.

In [72]:
df5[['Parameter Name','Address','Arithmetic Mean','Date Local','Units of Measure']]\
    .sort_values(by=['Date Local','Address']).head()

,Parameter Name,Address,Arithmetic Mean,Date Local,Units of Measure
251753,Wind Speed - Resultant,"Edgewood Chemical Biological Center (APG), ...",0.650000,2018-01-01,Knots
252113,Wind Direction - Resultant,"Edgewood Chemical Biological Center (APG), ...",277.565217,2018-01-01,Degrees Compass
86045,Wind Speed - Resultant,"151 NO SUNRISE BLVD, ROSEVILLE, CA",1.791667,2018-01-01,Knots
86410,Wind Direction - Resultant,"151 NO SUNRISE BLVD, ROSEVILLE, CA",182.333333,2018-01-01,Degrees Compass
32409,Wind Speed - Resultant,"201 CLINTON ROAD, JACKSON, CA 95642",0.762500,2018-01-01,Knots

Another important thing to keep in mind when creating the data model is to retain the Units of Measure value for each of the different types of data taht are being collected.

## Section 6: NHIS Data

The National Health Information Survey contains responses to survey questions done in an in-person interview format. I am using the individual survey responses to get data at the level of single individual.

In [77]:
df6 = pd.read_csv('personsxcsv2018.zip')
# The csv file has 72831 rows, but there are 602 different columns, so the output of df.info() is suppressed.
df6.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72831 entries, 0 to 72830
Data columns (total 602 columns):
FPX         72831 non-null int64
AGE_CHG     0 non-null float64
INTV_QRT    72831 non-null int64
SEX         72831 non-null int64
NOWAF       43253 non-null float64
FSPOUS2     30354 non-null float64
COHAB1      4082 non-null float64
COHAB2      1541 non-null float64
FCOHAB3     4082 non-null float64
ASTATFLG    56166 non-null float64
CSTATFLG    16665 non-null float64
FMX         72831 non-null int64
RRP         72831 non-null int64
FRRP        72831 non-null int64
ORIGIN_I    72831 non-null int64
HISPAN_I    72831 non-null int64
RACRECI3    72831 non-null int64
QCADULT     55 non-null float64
QCCHILD     22 non-null float64
R_MARITL    72831 non-null int64
MRACRPI2    72831 non-null int64
RACERPI2    72831 non-null int64
HISCODI3    72831 non-null int64
MRACBPI2    72831 non-null int64
AGE_P       72831 non-null int64
HHREFLG     29833 non-null object
RECTYPE     72831 non-null int64
SRVY_YR     72831 non-null int64
FMREFLG     30309 non-null object
FMRPFLG     30309 non-null object
PARENTS     72831 non-null int64
DAD_DEGP    17537 non-null float64
MOM_DEGP    22598 non-null float64
SIB_DEGP    1011 non-null float64
CDCMSTAT    60037 non-null float64
DAD_ED      16665 non-null float64
MOM_ED      16665 non-null float64
FMOTHER1    72831 non-null int64
FFATHER1    72831 non-null int64
HHX         72831 non-null int64
WTIA        72831 non-null float64
WTFA        72831 non-null int64
INTV_MON    72831 non-null int64
REGION      72831 non-null int64
PSTRAT      72831 non-null int64
PPSU        72831 non-null int64
PDMED12M    72831 non-null int64
PNMED12M    72831 non-null int64
PHOSPYR2    72831 non-null int64
PHCHM2W     72831 non-null int64
PHCPH2WR    72831 non-null int64
PHCDV2W     72831 non-null int64
P10DVYR     72831 non-null int64
HOSPNO_P    5885 non-null float64
HPNITE_P    5885 non-null float64
PHCHN2WP    954 non-null float64
PHCPN2WP    3725 non-null float64
PHCDN2WP    13952 non-null float64
PLAPLYLM    4192 non-null float64
PLAPLYUN    93 non-null float64
PSPEDEIS    16665 non-null float64
PSPEDEM     1375 non-null float64
PLAADL      70413 non-null float64
LABATH      1603 non-null float64
LADRESS     1603 non-null float64
LAEAT       1603 non-null float64
LABED       1603 non-null float64
LATOILT     1603 non-null float64
LAHOME      1603 non-null float64
PLAIADL     56166 non-null float64
PLAWKNOW    56166 non-null float64
PLAWKLIM    56166 non-null float64
PLAWALK     72831 non-null int64
PLAREMEM    72831 non-null int64
PLIMANY     72831 non-null int64
LAHCC1      1578 non-null float64
LAHCC2      1578 non-null float64
LAHCC3      1578 non-null float64
LAHCC4      1578 non-null float64
LAHCC5      1578 non-null float64
LAHCC6      1578 non-null float64
LAHCC8      1578 non-null float64
LAHCC9      1578 non-null float64
LAHCC10     1578 non-null float64
LAHCC11     1578 non-null float64
LAHCC12     1578 non-null float64
LAHCC13     1578 non-null float64
LAHCC90     1578 non-null float64
LAHCC91     1578 non-null float64
LAHCA1      9288 non-null float64
LAHCA2      9288 non-null float64
LAHCA3      9288 non-null float64
LAHCA4      9288 non-null float64
LAHCA5      9288 non-null float64
LAHCA6      9288 non-null float64
LAHCA7      9288 non-null float64
LAHCA8      9288 non-null float64
LAHCA9      9288 non-null float64
LAHCA10     9288 non-null float64
LAHCA11     9288 non-null float64
LAHCA12     9288 non-null float64
LAHCA13     9288 non-null float64
LAHCA15     9288 non-null float64
LAHCA16     9288 non-null float64
LAHCA17     9288 non-null float64
LAHCA18     9288 non-null float64
PHSTAT      72831 non-null int64
LATIME1     744 non-null float64
LAUNIT1     744 non-null float64
LATIME2     493 non-null float64
LAUNIT2     493 non-null float64
LATIME3     2124 non-null float64
LAUNIT3     2124 non-null float64
LATIME4     2209 non-null float64
LAUNIT4     2209 non-null float64
LATIME5     868 non-null float64
LAUNIT5     868 non-null float64
LATIME6     395 non-null float64
LAUNIT6     395 non-null float64
LATIME7     1103 non-null float64
LAUNIT7     1103 non-null float64
LATIME8     496 non-null float64
LAUNIT8     496 non-null float64
LATIME9     1061 non-null float64
LAUNIT9     1061 non-null float64
LATIME10    1034 non-null float64
LAUNIT10    1034 non-null float64
LATIME11    860 non-null float64
LAUNIT11    860 non-null float64
LATIME12    532 non-null float64
LAUNIT12    532 non-null float64
LATIME13    122 non-null float64
LAUNIT13    122 non-null float64
LATIME15    144 non-null float64
LAUNIT15    144 non-null float64
LATIME16    429 non-null float64
LAUNIT16    429 non-null float64
LATIME17    1341 non-null float64
LAUNIT17    1341 non-null float64
LATIME18    341 non-null float64
LAUNIT18    341 non-null float64
LCTIME1     54 non-null float64
LCUNIT1     54 non-null float64
LCTIME2     43 non-null float64
LCUNIT2     43 non-null float64
LCTIME3     376 non-null float64
LCUNIT3     376 non-null float64
LCTIME4     100 non-null float64
LCUNIT4     100 non-null float64
LCTIME5     73 non-null float64
LCUNIT5     73 non-null float64
LCTIME6     19 non-null float64
LCUNIT6     19 non-null float64
LCTIME8     160 non-null float64
LCUNIT8     160 non-null float64
LCTIME9     369 non-null float64
LCUNIT9     369 non-null float64
LCTIME10    51 non-null float64
LCUNIT10    51 non-null float64
LCTIME11    32 non-null float64
LCUNIT11    32 non-null float64
LCTIME12    345 non-null float64
LCUNIT12    345 non-null float64
LCTIME13    336 non-null float64
LCUNIT13    336 non-null float64
LCTIME90    80 non-null float64
LCUNIT90    80 non-null float64
LCTIME91    2 non-null float64
LCUNIT91    2 non-null float64
LATIME19    89 non-null float64
LATIME20    1410 non-null float64
LATIME21    351 non-null float64
LATIME22    251 non-null float64
LATIME23    993 non-null float64
LATIME24    262 non-null float64
LATIME25    340 non-null float64
LATIME26    18 non-null float64
LATIME27    22 non-null float64
LATIME28    62 non-null float64
LATIME29    17 non-null float64
LATIME30    195 non-null float64
LATIME31    74 non-null float64
LATIME32    190 non-null float64
LATIME33    11 non-null float64
LATIME34    5 non-null float64
LAUNIT19    89 non-null float64
LAUNIT20    1410 non-null float64
LAUNIT21    351 non-null float64
LAUNIT22    251 non-null float64
LAUNIT23    993 non-null float64
LAUNIT24    262 non-null float64
LAUNIT25    340 non-null float64
LAUNIT26    18 non-null float64
LAUNIT27    22 non-null float64
LAUNIT28    62 non-null float64
LAUNIT29    17 non-null float64
LAUNIT30    195 non-null float64
LAUNIT31    74 non-null float64
LAUNIT32    190 non-null float64
LAUNIT33    11 non-null float64
LAUNIT34    5 non-null float64
LAHCA90     9288 non-null float64
LATIME90    275 non-null float64
LAUNIT90    275 non-null float64
LAHCA91     9288 non-null float64
LATIME91    5 non-null float64
LAUNIT91    5 non-null float64
LCDURA1     54 non-null float64
LCDURA2     43 non-null float64
LCDURA3     376 non-null float64
LCDURA4     100 non-null float64
LCDURA5     73 non-null float64
LCDURA6     19 non-null float64
LCDURA8     160 non-null float64
LCDURA9     369 non-null float64
LCDURA10    51 non-null float64
LCDURA11    32 non-null float64
LCDURA12    345 non-null float64
LCDURA13    336 non-null float64
LCDURA90    80 non-null float64
LCDURA91    2 non-null float64
LADURA1     744 non-null float64
LADURA2     493 non-null float64
LADURA3     2124 non-null float64
LADURA4     2209 non-null float64
LADURA5     868 non-null float64
LADURA6     395 non-null float64
LADURA7     1103 non-null float64
LADURA8     496 non-null float64
LADURA9     1061 non-null float64
LADURA10    1034 non-null float64
LADURA11    860 non-null float64
LADURA12    532 non-null float64
LADURA13    122 non-null float64
LADURA15    144 non-null float64
LADURA16    429 non-null float64
LADURA17    1341 non-null float64
LADURA18    341 non-null float64
LADURA19    89 non-null float64
LADURA20    1410 non-null float64
LADURA21    351 non-null float64
LADURA22    251 non-null float64
LADURA23    993 non-null float64
LADURA24    262 non-null float64
LADURA25    340 non-null float64
LADURA26    18 non-null float64
LADURA27    22 non-null float64
LADURA28    62 non-null float64
LADURA29    17 non-null float64
LADURA30    195 non-null float64
LADURA31    74 non-null float64
LADURA32    190 non-null float64
LADURA33    11 non-null float64
LADURA34    5 non-null float64
LADURA90    275 non-null float64
LADURA91    5 non-null float64
LA1AR       72831 non-null int64
LCDURB1     54 non-null float64
LCDURB2     43 non-null float64
LCDURB3     376 non-null float64
LCDURB4     100 non-null float64
LCDURB5     73 non-null float64
LCDURB6     19 non-null float64
LCDURB8     160 non-null float64
LCDURB9     369 non-null float64
LCDURB10    51 non-null float64
LCDURB11    32 non-null float64
LCDURB12    345 non-null float64
LCDURB13    336 non-null float64
LCDURB90    80 non-null float64
LCDURB91    2 non-null float64
LCCHRC1     54 non-null float64
LCCHRC2     43 non-null float64
LCCHRC3     376 non-null float64
LCCHRC4     100 non-null float64
LCCHRC5     73 non-null float64
LCCHRC6     19 non-null float64
LCCHRC8     160 non-null float64
LCCHRC9     369 non-null float64
LCCHRC10    51 non-null float64
LCCHRC11    32 non-null float64
LCCHRC12    345 non-null float64
LCCHRC13    336 non-null float64
LCCHRC90    80 non-null float64
LCCHRC91    2 non-null float64
LADURB1     744 non-null float64
LADURB2     493 non-null float64
LADURB3     2124 non-null float64
LADURB4     2209 non-null float64
LADURB5     868 non-null float64
LADURB6     395 non-null float64
LADURB7     1103 non-null float64
LADURB8     496 non-null float64
LADURB9     1061 non-null float64
LADURB10    1034 non-null float64
LADURB11    860 non-null float64
LADURB12    532 non-null float64
LADURB13    122 non-null float64
LADURB15    144 non-null float64
LADURB16    429 non-null float64
LADURB17    1341 non-null float64
LADURB18    341 non-null float64
LADURB19    89 non-null float64
LADURB20    1410 non-null float64
LADURB21    351 non-null float64
LADURB22    251 non-null float64
LADURB23    993 non-null float64
LADURB24    262 non-null float64
LADURB25    340 non-null float64
LADURB26    18 non-null float64
LADURB27    22 non-null float64
LADURB28    62 non-null float64
LADURB29    17 non-null float64
LADURB30    195 non-null float64
LADURB31    74 non-null float64
LADURB32    190 non-null float64
LADURB33    11 non-null float64
LADURB34    5 non-null float64
LADURB90    275 non-null float64
LADURB91    5 non-null float64
LACHRC1     744 non-null float64
LACHRC2     493 non-null float64
LACHRC3     2124 non-null float64
LACHRC4     2209 non-null float64
LACHRC5     868 non-null float64
LACHRC6     395 non-null float64
LACHRC7     1103 non-null float64
LACHRC8     496 non-null float64
LACHRC9     1061 non-null float64
LACHRC10    1034 non-null float64
LACHRC11    860 non-null float64
LACHRC12    532 non-null float64
LACHRC13    122 non-null float64
LACHRC15    144 non-null float64
LACHRC16    429 non-null float64
LACHRC17    1341 non-null float64
LACHRC18    341 non-null float64
LACHRC19    89 non-null float64
LACHRC20    1410 non-null float64
LACHRC21    351 non-null float64
LACHRC22    251 non-null float64
LACHRC23    993 non-null float64
LACHRC24    262 non-null float64
LACHRC25    340 non-null float64
LACHRC26    18 non-null float64
LACHRC27    22 non-null float64
LACHRC28    62 non-null float64
LACHRC29    17 non-null float64
LACHRC30    195 non-null float64
LACHRC31    74 non-null float64
LACHRC32    190 non-null float64
LACHRC33    11 non-null float64
LACHRC34    5 non-null float64
LACHRC90    275 non-null float64
LACHRC91    5 non-null float64
LCONDRT     10866 non-null float64
LACHRONR    72831 non-null int64
LAHCA19_    9288 non-null float64
LAHCA20_    9288 non-null float64
LAHCA21_    9288 non-null float64
LAHCA22_    9288 non-null float64
LAHCA23_    9288 non-null float64
LAHCA24_    9288 non-null float64
LAHCA25_    9288 non-null float64
LAHCA26_    9288 non-null float64
LAHCA27_    9288 non-null float64
LAHCA28_    9288 non-null float64
LAHCA29_    9288 non-null float64
LAHCA30_    9288 non-null float64
LAHCA31_    9288 non-null float64
LAHCA32_    9288 non-null float64
LAHCA33_    9288 non-null float64
LAHCA34_    9288 non-null float64
LAHCA14A    9288 non-null float64
LTIME14A    224 non-null float64
LUNIT14A    224 non-null float64
LDURA14A    224 non-null float64
LDURB14A    224 non-null float64
LCHRC14A    224 non-null float64
LAHCC7A     1578 non-null float64
LCTIME7A    66 non-null float64
LCUNIT7A    66 non-null float64
LCDURA7A    66 non-null float64
LCDURB7A    66 non-null float64
LCCHRC7A    66 non-null float64
FINCINT     72831 non-null int64
PSAL        56166 non-null float64
PSEINC      56166 non-null float64
PSSRR       72831 non-null int64
PSSRRDB     2485 non-null float64
PSSRRD      1552 non-null float64
PPENS       72831 non-null int64
POPENS      72831 non-null int64
PSSI        72831 non-null int64
PSSID       1593 non-null float64
PTANF       72831 non-null int64
POWBEN      72831 non-null int64
PINTRSTR    72831 non-null int64
PDIVD       72831 non-null int64
PCHLDSP     72831 non-null int64
PINCOT      72831 non-null int64
PSSAPL      72831 non-null int64
PSDAPL      72831 non-null int64
TANFMYR     575 non-null float64
PWIC        50191 non-null float64
ELIGPWIC    72831 non-null int64
WIC_FLAG    1413 non-null float64
HIKINDNA    72831 non-null int64
HIKINDNB    72831 non-null int64
HIKINDNC    72831 non-null int64
HIKINDND    72831 non-null int64
HIKINDNE    72831 non-null int64
HIKINDNF    72831 non-null int64
HIKINDNG    72831 non-null int64
HIKINDNH    72831 non-null int64
HIKINDNI    72831 non-null int64
HIKINDNJ    72831 non-null int64
HIKINDNK    72831 non-null int64
MCAREPRB    1624 non-null float64
MCAIDPRB    5735 non-null float64
SINCOV      72831 non-null int64
MCPART      13878 non-null float64
MCCHOICE    12965 non-null float64
MCHMO       12965 non-null float64
MCPREM      4114 non-null float64
MCREF       12965 non-null float64
MCPARTD     13878 non-null float64
MACHMD      11766 non-null float64
MXCHNG      11766 non-null float64
MEDPREM     11766 non-null float64
MDPRINC     755 non-null float64
SSTYPEA     27319 non-null float64
SSTYPEB     27319 non-null float64
SSTYPEC     27319 non-null float64
SSTYPED     27319 non-null float64
SSTYPEE     27319 non-null float64
SSTYPEF     27319 non-null float64
SSTYPEG     27319 non-null float64
SSTYPEH     27319 non-null float64
SSTYPEI     27319 non-null float64
SSTYPEJ     27319 non-null float64
SSTYPEK     27319 non-null float64
SSTYPEL     27319 non-null float64
PRPOLH1     1487 non-null float64
PRPOLH2     90 non-null float64
PRCOOH1     42234 non-null float64
PRCOOH2     1651 non-null float64
PLNWRKS1    45156 non-null float64
PLNWRKS2    1746 non-null float64
PLNEXCH1    6993 non-null float64
PLNEXCH2    220 non-null float64
PLNPAY11    45156 non-null float64
PLNPAY21    45156 non-null float64
PLNPAY31    45156 non-null float64
PLNPAY41    45156 non-null float64
PLNPAY51    45156 non-null float64
PLNPAY61    45156 non-null float64
PLNPAY71    45156 non-null float64
PLNPAY12    1746 non-null float64
PLNPAY22    1746 non-null float64
PLNPAY32    1746 non-null float64
PLNPAY42    1746 non-null float64
PLNPAY52    1746 non-null float64
PLNPAY62    1746 non-null float64
PLNPAY72    1746 non-null float64
PLNPRE1     37067 non-null float64
PLNPRE2     1444 non-null float64
PLNMGD1     45156 non-null float64
PLNMGD2     1746 non-null float64
HDHP1       45156 non-null float64
HDHP2       1746 non-null float64
HSAHRA1     15571 non-null float64
HSAHRA2     216 non-null float64
MGCHMD1     45156 non-null float64
MGCHMD2     1746 non-null float64
MGPRMD1     24128 non-null float64
MGPRMD2     946 non-null float64
MGPYMD1     17795 non-null float64
MGPYMD2     663 non-null float64
PCPREQ1     45156 non-null float64
PCPREQ2     1746 non-null float64
PRRXCOV1    45156 non-null float64
PRRXCOV2    1746 non-null float64
PRDNCOV1    45156 non-null float64
PRDNCOV2    1746 non-null float64
FCOVCONF    44055 non-null float64
CHXCHNG     560 non-null float64
STRFPRM1    560 non-null float64
CHPRINC     154 non-null float64
STDOC1      560 non-null float64
OPXCHNG     579 non-null float64
STRFPRM2    579 non-null float64
SSPRINC     83 non-null float64
STDOC2      579 non-null float64
OGXCHNG     174 non-null float64
STRFPRM3    174 non-null float64
OGPRINC     63 non-null float64
STDOC3      174 non-null float64
MILSPC1     3121 non-null float64
MILSPC2N    3910 non-null float64
MILSPC3     3113 non-null float64
MILSPC4     3112 non-null float64
MILMANN     2046 non-null float64
HILAST2     5615 non-null float64
HISTOP1     5615 non-null float64
HISTOP2     5615 non-null float64
HISTOP3     5615 non-null float64
HISTOP4     5615 non-null float64
HISTOP5     5615 non-null float64
HISTOP6     5615 non-null float64
HISTOP7     5615 non-null float64
HISTOP8     5615 non-null float64
HISTOP9     5615 non-null float64
HISTOP10    5615 non-null float64
HINOTYR     66423 non-null float64
HINOTMYR    2484 non-null float64
FHICHNG     63922 non-null float64
FHIKDBA     9708 non-null float64
FHIKDBB     9708 non-null float64
FHIKDBC     9708 non-null float64
FHIKDBD     9708 non-null float64
FHIKDBE     9708 non-null float64
FHIKDBF     9708 non-null float64
FHIKDBG     9708 non-null float64
FHIKDBH     9708 non-null float64
FHIKDBI     9708 non-null float64
FHIKDBJ     9708 non-null float64
FHIKDBK     9708 non-null float64
HCSPFYR     72831 non-null int64
MEDBILL     72831 non-null int64
MEDBPAY     72831 non-null int64
MEDBNOP     10357 non-null float64
FSA         72831 non-null int64
EXCHPR1     43855 non-null float64
EXCHPR2     1746 non-null float64
PLEXCHOP    579 non-null float64
PLEXCHOG    174 non-null float64
PRIVATE     72831 non-null int64
MEDICARE    72831 non-null int64
MEDICAID    72831 non-null int64
SCHIP       72831 non-null int64
MILITARN    72831 non-null int64
MILSPC2I    3058 non-null float64
IHS         72831 non-null int64
OTHPUB      72831 non-null int64
OTHGOV      72831 non-null int64
SINGLE      72831 non-null int64
HICOSTR1    37067 non-null float64
HICOSTR2    1444 non-null float64
MCADVR      4114 non-null float64
PXCHNG      1196 non-null float64
PSTDOC      1196 non-null float64
PSTRFPRM    1196 non-null float64
PSSPRINC    755 non-null float64
PLEXCHPR    1196 non-null float64
PRFLG       1196 non-null float64
HISTOP11    5615 non-null float64
HISTOP12    5615 non-null float64
HISTOP13    5615 non-null float64
HISTOP14    5615 non-null float64
HISTOP15    5615 non-null float64
EXCHANGE    45105 non-null float64
MAFLG       121 non-null float64
CHFLG       2 non-null float64
OPFLG       5 non-null float64
OGFLG       0 non-null float64
WHONAM1     45156 non-null float64
WHONAM2     1746 non-null float64
NOTCOV      72831 non-null int64
PRPLPLUS    44764 non-null float64
PWRKBR1     4320 non-null float64
COVER       59918 non-null float64
COVER65O    12913 non-null float64
COVER65     12911 non-null float64
REGIONBR    72831 non-null int64
WHYNOWKP    20763 non-null float64
GEOBRTH     72831 non-null int64
YRSINUS     10855 non-null float64
CITIZENP    72831 non-null int64
DOINGLWP    56166 non-null float64
WRKLYR1     56166 non-null float64
WRKHRS2     34921 non-null float64
PLBORN      72831 non-null int64
HEADST      6017 non-null float64
HEADSTV1    16114 non-null float64
ARMFVER     259 non-null float64
ARMFEV      56166 non-null float64
ARMFFC      5131 non-null float64
VACOV       4234 non-null float64
WRKFTALL    7890 non-null float64
WRKMYR      36984 non-null float64
HIEMPOF     34814 non-null float64
EDUC1       72831 non-null int64
ERNYR_P     36984 non-null float64
ARMFTM7P    375 non-null float64
ARMFTM1P    4641 non-null float64

In [108]:
[x for x in df6.columns if '14' in x]

['LAHCA14A',
 'LTIME14A',
 'LUNIT14A',
 'LDURA14A',
 'LDURB14A',
 'LCHRC14A',
 'HISTOP14']

In [109]:
# df6.loc[:,df6.isnull().sum()>=72000]
df6[['LAHCA14A',
 'LTIME14A',
 'LUNIT14A',
 'LDURA14A',
 'LDURB14A',
 'LCHRC14A',
 'HISTOP14']]

       LAHCA14A  LTIME14A  LUNIT14A  LDURA14A  LDURB14A  LCHRC14A  HISTOP14
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN
2           NaN       NaN       NaN       NaN       NaN       NaN       NaN
3           NaN       NaN       NaN       NaN       NaN       NaN       NaN
4           NaN       NaN       NaN       NaN       NaN       NaN       NaN
5           NaN       NaN       NaN       NaN       NaN       NaN       NaN
6           NaN       NaN       NaN       NaN       NaN       NaN       NaN
7           NaN       NaN       NaN       NaN       NaN       NaN       NaN
8           NaN       NaN       NaN       NaN       NaN       NaN       NaN
9           NaN       NaN       NaN       NaN       NaN       NaN       NaN
10          NaN       NaN       NaN       NaN       NaN       NaN       NaN
11          2.0       NaN       NaN       NaN       NaN       NaN       NaN
12          NaN       NaN       NaN       NaN       NaN       NaN       NaN
13          NaN       NaN       NaN       NaN       NaN       NaN       NaN
14          NaN       NaN       NaN       NaN       NaN       NaN       NaN
15          NaN       NaN       NaN       NaN       NaN       NaN       NaN
16          NaN       NaN       NaN       NaN       NaN       NaN       NaN
17          NaN       NaN       NaN       NaN       NaN       NaN       NaN
18          NaN       NaN       NaN       NaN       NaN       NaN       NaN
19          NaN       NaN       NaN       NaN       NaN       NaN       NaN
20          NaN       NaN       NaN       NaN       NaN       NaN       NaN
21          NaN       NaN       NaN       NaN       NaN       NaN       NaN
22          NaN       NaN       NaN       NaN       NaN       NaN       NaN
23          NaN       NaN       NaN       NaN       NaN       NaN       NaN
24          NaN       NaN       NaN       NaN       NaN       NaN       NaN
25          NaN       NaN       NaN       NaN       NaN       NaN       NaN
26          NaN       NaN       NaN       NaN       NaN       NaN       NaN
27          NaN       NaN       NaN       NaN       NaN       NaN       NaN
28          2.0       NaN       NaN       NaN       NaN       NaN       NaN
29          NaN       NaN       NaN       NaN       NaN       NaN       NaN
...         ...       ...       ...       ...       ...       ...       ...
72801       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72802       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72803       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72804       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72805       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72806       2.0       NaN       NaN       NaN       NaN       NaN       NaN
72807       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72808       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72809       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72810       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72811       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72812       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72813       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72814       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72815       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72816       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72817       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72818       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72819       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72820       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72821       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72822       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72823       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72824       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72825       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72826       2.0       NaN       NaN       NaN       NaN       NaN       2.0
72827       2.0       NaN       NaN       NaN       NaN       NaN       NaN
72828       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72829       NaN       NaN       NaN       NaN       NaN       NaN       NaN
72830       NaN       NaN       NaN       NaN       NaN       NaN       NaN

[72831 rows x 7 columns]

Ideas for project outcome: 
1. use the past two weeks type variable (phone calls, visits) to marry with AQI data
2. use past 1 - 3 of AQI data to marry with specific problem types that began the year after AQI
3. convert into structure that supports visualizing the AQI and specific functional limitations together on a map

### NHIS Data Column Description and Understanding

I am marking the columns I plan to use in the final model in bold.

- **FPX: Person Number (within family). FMX is the family number. I think this table should contain one row per FMX/FPX. An individual is identified FPX+FMX+HHX+SRVY_YR**
- **HHX: Household number, identifies individual households**
- **INTV_MON: the interview month**
- **FMX: Family number. Each FPX is associated with an FMX ID**
- **SRVY_YR: the year of the survey**
- **REGION: northeast, midwest, south, west**
- **AGE_P: the person's age in years. 00 is under 1 yr old, 1-84 are the values, 85+ is recorded as 85**
- **QCADULT: a flag for where adult data was removed for quality reasons. Use this as a cleaning step**
- **QCCHILD: a flag for where child data was remvoed for quality reasons. Use this as a cleaning step**
- **PLAADL: does person need help with activities of daily living due to physical, mental, or emotional problems? 1 Yes, 2 no, 7 refused, 8 not ascertained, 9 don't know**
- **PLAIADL: does person need help with routine needs (everyday chores, doing necessary business, shopping, getting around) because of physical mental, or emotional problems? 1 Yes, 2 no, 7 refused, 8 not ascertained, 9 don't know**
- **PLAWKNOW: does a physical, mental or emotional problem currently keep you from working a job? 1 Yes, 2 no, 7 refused, 8 not ascertained, 9 don't know**
- **PLAWKLIM: is person limited in the kind or amount of work they can do? 0 Unable to work, 1 limited in work, 2 not limited in work, 7 refused, 8 not ascertained, 9 don't know
- **PLAWALK: do you have difficulty walking without using any special - equiptment? 1 Yes, 2 no, 7 refused, 8 not ascertained, 9 don't know**
- **PLAREMEM: is person limited in any way because of difficulty remember or because they experience periods of confusion?  Yes, 2 no, 7 refused, 8 not ascertained, 9 don't know**
- **PLIMANY: Is person limited in any way in any activities because of physical, emotional, or mental problems? 0 limitation previously mentioned, 1 Yes, limited in some other way, 2 not limited in any way,7 refused, 8 not ascertained, 9 don't know**
- **LAIAR: Any limitations from any of questions about limitations (PLAPLYLM; PSPEDEIS; PLAADL; PLAIADL; PLAWKNOW; PLAWKLIM; PLAWALK; PLAREMEM; PLIMANY). 1 limited in any way, 2 not limited in any way, 3 unknown if limited**
- **LAHCC1: under 18 and limited by vision problem 1 Mentioned, 2 Not mentioned, 7 refused 8 not ascertained 9 don't know**
- **LAHCC2: hearing problem**
- **LAHCC3: speech problem**
- **LAHCC4: asthma, breathing problem**
- **LAHCC5: birth defect**
- **LAHCC6: injury**
- **LAHCC7: intellectual disability, mental retardation**
- **LAHCC8: other development problem, cerebral palsy**
- **LAHCC9: mental/emotional/behavioral problem**
- **LAHCC10: bone, joint, muscle problem**
- **LAHCC11: epilepsy, seizure**
- **LAHCC12: learning disability**
- **LAHCC13: attention deficit/hyperactivity disorder; ADD/ADHD**
- **LAHCC90: other 1**
- **LAHCC91: other 2**
- **LCTIME1: how long had vision problem? 1-94 1-94; 95 95+; 96 Since birth; 97 Refused; 98 Not ascertained; 99 Don't know**
- **LCUNIT1: unit of time associated with LCTIME1 1 Day(s); 2 Week(s); 3 Month(s); 4 Year(s); 6 Since birth; 7 Refused; 8 Not ascertained; 9 Don't know**
- **LCTIME2: how long had hearing problem?**
- **LCUNIT2: number of units for LCTIME2**
- **LCTIME(X): how long had LAHCC(X)?**
- **LCUNIT(X): unit of time for LAHCC(X)**
- **LAHCA1: adult vision problem**
- **LAHCA2: adult hearing problem**
- **LAHCA3: adult arthritis; rheumatism**
- **LAHCA4: adult back/neck problem**
- **LAHCA5: adult fracture; bone/joint injury**
- **LAHCA6: adult other injury**
- **LAHCA7: adult heart problem**
- **LAHCA8: adult stroke**
- **LAHCA9: adult hypertension; high blood pressure**
- **LAHCA10: adult diabetes**
- **LAHCA11: adult lung/breathing problem/emphysema**
- **LAHCA12: adult cancer**
- **LAHCA13: adult birth defect**
- **LAHCA14: adult intellectual disability; mental retardation**
- **LAHCA15: adult other development problem; cerebral palsy**
- **LAHCA16: adult senility; dementia; Alzheimer's**
- **LAHCA17: adult depression; anxiety; emotional problem**
- **LAHCA18: adult weight problem; overweight; obesity**
- **LAHCA19_: adult missing limbs (fingers, toes, digits); amutee**
- **LAHCA20_: adult musculoskeletal system; connective tissue**
- **LAHCA21_: adult circulation problem; circulatory system; blood clots**
- **LAHCA22_: adult endocrine; nutritional; metabolic**
- **LAHCA23_: adult nervous system; sensory organ condition**
- **LAHCA24_: adult digestion problem**
- **LAHCA25_: adult genitourinary system**
- **LAHCA26_: adult skin, subcutaneous system promblem**
- **LAHCA27_: adult blood, blood-forming organ**
- **LAHCA28_: adult benign tumor/cyst**
- **LAHCA29_: adult alcohol/drug/substance abuse problem**
- **LAHCA30_: adult metnal illness; ADD; bipolar; schizophrenia**
- **LAHCA31_: adult surgical after-effects; medical treatment; operation; surgery**
- **LAHCA32_: adult elderly, old age, aging**
- **LAHCA33_: adult fatigue; tiredness; weakness**
- **LAHCA34_: adult pregnancy**
- **LAHCA90: adult other problem 1**
- **LAHCA91: adult other problem 2**
- **LATIMEXX: how long have you had problem X? LATIME14A is different**
- **LAUNITXX: unit of time associated with LATIMEXX. LAUNIT14A is different**
- **LACHRONR: all persons, functional limitation, chronic condition 0 Not limited in any way (including unknown if limited) 1 Limited; caused by at least one chronic condition 2 Limited; not caused by chronic condition 3 Limited; unknown if condition is chronic**
- **PHSTAT: reported health status 1 Excellent 2 Very good 3 Good 4 Fair 5 Poor 7 Refused 8 Not ascertained 9 Don't know**
- **PHOSPYR2: has been in hospital overnight in past 12 months 1 Yes 2 No 7 Refused 8 Not ascertained 9 Don't know**
- **HOSPNO: number of times in hospital overnight in last 12 months 01-365 1-365 times 997 Refused 998 Not ascertained 999 Don't know**
- **HPNITE: number of nights in hospital past 12 months 01-365 1-365 nights 997 Refused 998 Not ascertained 999 Don't know**
- **PHCPH2WR: got advice/test results by phone past 2 weeks 1 Yes 2 No 7 Refused 8 Not ascertained 9 Don't know**
- **PHCDV2W: saw health professional in office/ed/clinic in past 2 weeks  1 Yes 2 No 7 Refused 8 Not ascertained 9 Don't know**
- **PHCDVN2W: number of times visited health professional in office/ed/clinic past 2 weeks 1-50 1-50 times 97 Refused 98 Not ascertained 99 Don't know**
- **NOTCOV: health insurance coverage 1 Not covered 2 Covered 7 Refused 8 Not ascertained 9 Don't know**
- **HCSPFYR: amount family spent on medical care in past 12months 0 Zero 1 Less than $500 2 $500 - $1,999 3 $2,000 - $2,999 4 $3,000 - $4,999 5 $5,000 or more 7 Refused 8 Not ascertained 9 Don't know**
- **SEX: 1 is male, 2 is female**

## Cleaning steps:
1. Calculate the duration of problems in days using  TIME and UNIT columns for each problem.
2. Combine problems for adults and children into single column

In [125]:
((df6.groupby(['CITIZENP','EDUC1'])['FPX'].count())/len(df6[df6['CITIZENP']==1])).loc[(1,[14,18,20,21])]

CITIZENP  EDUC1
1         14       0.176329
          18       0.158886
          20       0.011771
          21       0.012285
Name: FPX, dtype: float64